-- AlterTable
ALTER TABLE "Job" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "JobLog" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Queue" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id" DROP DEFAULT;
